import os
from dotenv import load_dotenv

# Load variables from .env file if it exists
load_dotenv()

# ==========================================
# 1. Target Tracking Criteria
# ==========================================
# The keywords to match in job titles (case-insensitive, whole-word matching)
KEYWORDS = [
    # Flutter / Mobile
    "Flutter",
    "Android",
    "iOS",
    "Dart",
    "Java",
    "Kotlin",
    "Flutter/Android/iOS/Dart",
    "Flutter Developer",
    "Flutter Engineer",
    "Android Developer",
    "Android Engineer",
    "Mobile Developer",
    "Mobile Engineer",

    # AI Application Development
    "AI App Developer",
    "AI Mobile Developer",
    "Mobile AI Engineer",
    "AI Engineer",
    "AI Integration Engineer",
    "Applied AI Engineer",
    "AI Software Engineer",
    "LLM Engineer",
    "LLM Application Developer",
    "GenAI Engineer",

    # # Full Stack
    # "Full Stack Developer",
    # "Full Stack Engineer",
    # "Backend Developer",
    # "Backend Engineer",

    # # React
    # "React Developer",
    # "React Engineer",
    # "React.js",
    # "ReactJS",
    # "Next.js"
]

# Time limit in hours for jobs posted
JOB_LOOKBACK_HOURS = 24

# Location filtering: If True, only jobs matching 'remote' or 'hybrid' in location/title are processed
ONLY_REMOTE_OR_HYBRID = True

# Truly global search locations and domains (including Europe, EU & UAE)
LINKEDIN_GLOBAL_LOCATIONS = ["Worldwide", "Europe", "European Union", "United Arab Emirates", "Dubai"]

# Curated list of top tech-hiring countries for fast and cost-efficient searches
INDEED_CURATED_DOMAINS = [
    "www.indeed.com",      # United States
    "uk.indeed.com",       # United Kingdom
    "ca.indeed.com",       # Canada
    "au.indeed.com",       # Australia
    "de.indeed.com",       # Germany
    "fr.indeed.com",       # France
    "in.indeed.com",       # India
    "sg.indeed.com",       # Singapore
    "kr.indeed.com",       # South Korea
    "jp.indeed.com",       # Japan
    "nl.indeed.com",       # Netherlands
    "se.indeed.com",       # Sweden
    "ie.indeed.com",       # Ireland
    "ae.indeed.com",       # United Arab Emirates
    "ch.indeed.com"        # Switzerland
]

# Comprehensive list of all 58 country domains supported by Indeed
INDEED_ALL_DOMAINS = [
    "www.indeed.com", "uk.indeed.com", "ca.indeed.com", "au.indeed.com", "de.indeed.com",
    "fr.indeed.com", "in.indeed.com", "sg.indeed.com", "kr.indeed.com", "jp.indeed.com",
    "nl.indeed.com", "se.indeed.com", "ie.indeed.com", "ae.indeed.com", "ch.indeed.com",
    "ar.indeed.com", "at.indeed.com", "be.indeed.com", "br.indeed.com", "cl.indeed.com",
    "co.indeed.com", "cr.indeed.com", "cz.indeed.com", "dk.indeed.com", "ec.indeed.com",
    "eg.indeed.com", "fi.indeed.com", "gr.indeed.com", "hk.indeed.com", "hu.indeed.com",
    "id.indeed.com", "il.indeed.com", "it.indeed.com", "lu.indeed.com", "my.indeed.com",
    "mx.indeed.com", "ma.indeed.com", "nz.indeed.com", "no.indeed.com", "om.indeed.com",
    "pk.indeed.com", "pa.indeed.com", "pe.indeed.com", "ph.indeed.com", "pl.indeed.com",
    "pt.indeed.com", "qa.indeed.com", "ro.indeed.com", "sa.indeed.com", "za.indeed.com",
    "es.indeed.com", "tw.indeed.com", "th.indeed.com", "tr.indeed.com", "ua.indeed.com",
    "uy.indeed.com", "ve.indeed.com", "vn.indeed.com"
]

# Set the active Indeed domains list. Switch to INDEED_ALL_DOMAINS if you want full global coverage.
INDEED_GLOBAL_DOMAINS = INDEED_CURATED_DOMAINS


# ==========================================
# 2. Portal Mappings
# ==========================================
# Dictionary of company names mapping to their ATS and board token/ID.
#
# Supported ATS & API types (via jobhive-py adapter):
# 1. Multi-tenant ATS: greenhouse, lever, ashby, smartrecruiters, workable, rippling,
#    personio, gem, join_com, icims, jazzhr, breezy, teamtailor, pinpoint, bamboohr,
#    cornerstone, recruitee, recruiterbox, eightfold, avature, phenom, workday, oracle,
#    successfactors, taleo, mercor
# 2. Custom big-tech APIs: amazon, apple, google, tiktok, uber
# 3. National public-sector aggregators: bundesagentur (DE), arbetsformedlingen (SE), eures (EU)
# 4. Hybrid job boards: welcometothejungle
# 5. Browser-required (set JOBHIVE_USE_BROWSERBASE=1, BROWSERBASE_API_KEY, BROWSERBASE_PROJECT_ID): meta, tesla
#
COMPANY_BOARDS = {
    # --- AI Startups ---
    'Abridge': {'ats': 'ashby', 'token': 'abridge'},
    'Anthropic': {'ats': 'greenhouse', 'token': 'anthropic'},
    'Anyscale': {'ats': 'lever', 'token': 'anyscale'},
    'Baseten': {'ats': 'ashby', 'token': 'baseten'},
    'Character.AI': {'ats': 'ashby', 'token': 'character'},
    'Cognition': {'ats': 'ashby', 'token': 'cognition'},
    'Cohere': {'ats': 'ashby', 'token': 'cohere'},
    'Decagon': {'ats': 'ashby', 'token': 'decagon'},
    'DeepL': {'ats': 'ashby', 'token': 'deepl'},
    'ElevenLabs': {'ats': 'ashby', 'token': 'elevenlabs'},
    'Ema': {'ats': 'ashby', 'token': 'ema'},
    'Harvey': {'ats': 'ashby', 'token': 'harvey'},
    'HeyGen': {'ats': 'greenhouse', 'token': 'heygen'},
    'Hugging Face': {'ats': 'workable', 'token': 'huggingface'},
    'Imbue': {'ats': 'greenhouse', 'token': 'imbue'},
    'LangChain': {'ats': 'ashby', 'token': 'langchain'},
    'LlamaIndex': {'ats': 'ashby', 'token': 'llamaindex'},
    'MAGIC': {'ats': 'workable', 'token': 'magic-careers'},
    'Magic': {'ats': 'greenhouse', 'token': 'magic'},
    'Mistral AI': {'ats': 'lever', 'token': 'mistral'},
    'OpenAI': {'ats': 'ashby', 'token': 'openai'},
    'Perplexity': {'ats': 'ashby', 'token': 'perplexity'},
    'Runway': {'ats': 'ashby', 'token': 'runway-ml'},
    'Synthesia': {'ats': 'bamboohr', 'token': 'synthesia'},
    'Together AI': {'ats': 'greenhouse', 'token': 'togetherai'},
    'adept': {'ats': 'bamboohr', 'token': 'adept'},
    'openai': {'ats': 'bamboohr', 'token': 'openai'},
    # --- SaaS / Productivity ---
    'Airtable': {'ats': 'greenhouse', 'token': 'airtable'},
    'Asana': {'ats': 'greenhouse', 'token': 'asana'},
    'Calendly': {'ats': 'greenhouse', 'token': 'calendly'},
    'Canva': {'ats': 'smartrecruiters', 'token': 'Canva'},
    'ClickUp': {'ats': 'ashby', 'token': 'clickup'},
    'Coda': {'ats': 'lever', 'token': 'Coda'},
    'Dropbox': {'ats': 'greenhouse', 'token': 'dropbox'},
    'Figma': {'ats': 'greenhouse', 'token': 'figma'},
    'HubSpot': {'ats': 'greenhouse', 'token': 'hubspotjobs'},
    'Hubspot': {'ats': 'greenhouse', 'token': 'hubspot'},
    'Linear': {'ats': 'ashby', 'token': 'linear'},
    'Loom': {'ats': 'ashby', 'token': 'loom'},
    'Miro': {'ats': 'ashby', 'token': 'miro'},
    'Monday': {'ats': 'personio', 'token': 'monday'},
    'Notion': {'ats': 'ashby', 'token': 'notion'},
    'Salesforce': {'ats': 'workday', 'token': 'salesforce.wd12.myworkdayjobs.com/wday/cxs/salesforce/External_Career_Site'},
    'Slack': {'ats': 'workday', 'token': 'salesforce.wd12.myworkdayjobs.com/wday/cxs/salesforce/slack'},
    'Zapier': {'ats': 'ashby', 'token': 'zapier'},
    'Zoom': {'ats': 'workday', 'token': 'zoom.wd5.myworkdayjobs.com/wday/cxs/zoom/zoom'},
    'asana': {'ats': 'bamboohr', 'token': 'asana'},
    'calendly': {'ats': 'smartrecruiters', 'token': 'calendly'},
    'framer': {'ats': 'personio', 'token': 'framer'},
    'zapier': {'ats': 'bamboohr', 'token': 'zapier'},
    # --- Developer Tools & Infrastructure ---
    'CircleCI': {'ats': 'greenhouse', 'token': 'circleci'},
    'Cloudflare': {'ats': 'greenhouse', 'token': 'cloudflare'},
    'Cockroach Labs': {'ats': 'greenhouse', 'token': 'cockroachlabs'},
    'Datadog': {'ats': 'greenhouse', 'token': 'datadog'},
    'Docker': {'ats': 'bamboohr', 'token': 'docker'},
    'Fastly': {'ats': 'greenhouse', 'token': 'fastly'},
    'Fivetran': {'ats': 'greenhouse', 'token': 'fivetran'},
    'GitHub': {'ats': 'workable', 'token': 'github'},
    'GitLab': {'ats': 'greenhouse', 'token': 'gitlab'},
    'Grafana Labs': {'ats': 'greenhouse', 'token': 'grafanalabs'},
    'Netlify': {'ats': 'bamboohr', 'token': 'netlify'},
    'Prisma': {'ats': 'rippling', 'token': 'prisma-careers'},
    'Pulumi': {'ats': 'greenhouse', 'token': 'pulumicorporation'},
    'Redis': {'ats': 'ashby', 'token': 'redis'},
    'Sentry': {'ats': 'ashby', 'token': 'sentry'},
    'Snowflake': {'ats': 'ashby', 'token': 'snowflake'},
    'Snyk': {'ats': 'ashby', 'token': 'snyk'},
    'Supabase': {'ats': 'ashby', 'token': 'supabase'},
    'Temporal': {'ats': 'ashby', 'token': 'temporal'},
    'Vercel': {'ats': 'greenhouse', 'token': 'vercel'},
    'Wiz': {'ats': 'ashby', 'token': 'wiz'},
    'pulumi': {'ats': 'bamboohr', 'token': 'pulumi'},
    # --- Fintech ---
    'Adyen': {'ats': 'greenhouse', 'token': 'adyen'},
    'Affirm': {'ats': 'greenhouse', 'token': 'affirm'},
    'Airwallex': {'ats': 'ashby', 'token': 'airwallex'},
    'Bolt': {'ats': 'ashby', 'token': 'bolt'},
    'Bolt.new': {'ats': 'greenhouse', 'token': 'stackblitz'},
    'Brex': {'ats': 'greenhouse', 'token': 'brex'},
    'Carta': {'ats': 'greenhouse', 'token': 'carta'},
    'Chime Financial, Inc': {'ats': 'greenhouse', 'token': 'chime'},
    'Deel': {'ats': 'ashby', 'token': 'deel'},
    'Gemini': {'ats': 'greenhouse', 'token': 'gemini'},
    'Gusto': {'ats': 'breezy', 'token': 'gusto'},
    'Gusto, Inc.': {'ats': 'greenhouse', 'token': 'gusto'},
    'Jeeves': {'ats': 'lever', 'token': 'tryjeeves'},
    'Kraken': {'ats': 'lever', 'token': 'kraken123'},
    'Kraken Digital Asset Exchange': {'ats': 'lever', 'token': 'kraken'},
    'Ledger': {'ats': 'ashby', 'token': 'ledger'},
    'Melio': {'ats': 'greenhouse', 'token': 'melio'},
    'Mercury': {'ats': 'ashby', 'token': 'mercury'},
    'Monzo': {'ats': 'greenhouse', 'token': 'monzo'},
    'Ramp': {'ats': 'ashby', 'token': 'ramp'},
    'Rippling': {'ats': 'rippling', 'token': 'rippling'},
    'Robinhood': {'ats': 'greenhouse', 'token': 'robinhood'},
    'Stripe': {'ats': 'greenhouse', 'token': 'stripe'},
    'gusto': {'ats': 'jazzhr', 'token': 'gusto'},
    'ramp': {'ats': 'jazzhr', 'token': 'ramp'},
    # --- Cloud & Infrastructure ---
    'Azure': {'ats': 'workable', 'token': 'azure'},
    'Backblaze External Website': {'ats': 'greenhouse', 'token': 'backblaze'},
    'CoreWeave': {'ats': 'greenhouse', 'token': 'coreweave'},
    'CoreWeave Europe': {'ats': 'greenhouse', 'token': 'coreweaveu'},
    'Databricks': {'ats': 'greenhouse', 'token': 'databricks'},
    'LAMBDA': {'ats': 'smartrecruiters', 'token': 'lambda'},
    'Lambda': {'ats': 'ashby', 'token': 'lambda'},
    'Linode': {'ats': 'breezy', 'token': 'linode'},
    'Render': {'ats': 'ashby', 'token': 'render'},
    # --- Mobile-First / Consumer Tech ---
    'Airbnb': {'ats': 'greenhouse', 'token': 'airbnb'},
    'Bumble': {'ats': 'ashby', 'token': 'bumble'},
    'Bumble Inc.': {'ats': 'lever', 'token': 'bumbleinc'},
    'ClassPass': {'ats': 'greenhouse', 'token': 'classpass'},
    'Contractor Jobs at Airbnb': {'ats': 'greenhouse', 'token': 'contractorjobs'},
    'DoorDash Australia': {'ats': 'greenhouse', 'token': 'doordashaustralia'},
    'DoorDash Canada': {'ats': 'greenhouse', 'token': 'doordashcanada'},
    'DoorDash High Volume': {'ats': 'greenhouse', 'token': 'high-volume'},
    'DoorDash India': {'ats': 'greenhouse', 'token': 'doordashindia'},
    'DoorDash Quebec': {'ats': 'greenhouse', 'token': 'doordashquebec'},
    'DoorDash USA': {'ats': 'greenhouse', 'token': 'doordashusa'},
    'Duolingo': {'ats': 'breezy', 'token': 'duolingo'},
    'Headspace': {'ats': 'greenhouse', 'token': 'hs'},
    'Headspace Providers': {'ats': 'greenhouse', 'token': 'headspaceproviders'},
    'Headspace Sourcing': {'ats': 'greenhouse', 'token': 'headspacesourcing'},
    'Hopper': {'ats': 'bamboohr', 'token': 'hopper'},
    'Instacart': {'ats': 'smartrecruiters', 'token': 'instacart'},
    'Instagram': {'ats': 'workable', 'token': 'instagram'},
    'Lyft': {'ats': 'smartrecruiters', 'token': 'lyft'},
    'Match Group': {'ats': 'lever', 'token': 'matchgroup'},
    'Pinterest': {'ats': 'greenhouse', 'token': 'pinterest'},
    'Reddit': {'ats': 'greenhouse', 'token': 'reddit'},
    'Spotify': {'ats': 'lever', 'token': 'spotify'},
    'instacart': {'ats': 'greenhouse', 'token': 'instacart'},
    'lyft': {'ats': 'greenhouse', 'token': 'lyft'},
    'whatsapp': {'ats': 'workable', 'token': 'whatsapp'},

    # --- Added Direct Boards ---
    'Vanta': {'ats': 'ashby', 'token': 'vanta'},
    'Retool': {'ats': 'gem', 'token': 'retool'},
    'Plaid': {'ats': 'greenhouse', 'token': 'plaid'},
    'Verkada': {'ats': 'greenhouse', 'token': 'verkada'},
    'Scale AI': {'ats': 'greenhouse', 'token': 'scaleai'},
    'Harness': {'ats': 'greenhouse', 'token': 'harness'},
    'Postman': {'ats': 'greenhouse', 'token': 'postman'},
    'Faire': {'ats': 'greenhouse', 'token': 'faire'},
    'Checkr': {'ats': 'greenhouse', 'token': 'checkr'},
    'Remote': {'ats': 'greenhouse', 'token': 'remote'},
    'Weaviate': {'ats': 'greenhouse', 'token': 'weaviate'},
    'Orca Security': {'ats': 'greenhouse', 'token': 'orcasecurity'},
    'Whimsical': {'ats': 'ashby', 'token': 'whimsical'},
    'Webflow': {'ats': 'greenhouse', 'token': 'webflow'},
    'Tailscale': {'ats': 'greenhouse', 'token': 'tailscale'},
    'Railway': {'ats': 'ashby', 'token': 'railway'},
    'Anysphere (Cursor)': {'ats': 'ashby', 'token': 'anysphere'},
    'Atlassian': {'ats': 'lever', 'token': 'atlassian'},
    'Attentive': {'ats': 'greenhouse', 'token': 'attentive'},
    'Clearbit': {'ats': 'lever', 'token': 'clearbit'},
    'dbt Labs': {'ats': 'greenhouse', 'token': 'dbtlabs'},
    'DataStax': {'ats': 'greenhouse', 'token': 'datastax'},
    'Elastic': {'ats': 'greenhouse', 'token': 'elastic'},
    'HashiCorp': {'ats': 'greenhouse', 'token': 'hashicorp'},
    'Klaviyo': {'ats': 'greenhouse', 'token': 'klaviyo'},
    'LaunchDarkly': {'ats': 'greenhouse', 'token': 'launchdarkly'},
    'Modal': {'ats': 'ashby', 'token': 'modal'},
    'Pinecone': {'ats': 'ashby', 'token': 'pinecone'},
    'PlanetScale': {'ats': 'greenhouse', 'token': 'planetscale'},
    '1Password': {'ats': 'lever', 'token': '1password'},
    'Replit': {'ats': 'ashby', 'token': 'replit'},
    'Resend': {'ats': 'ashby', 'token': 'resend'},
    'Sourcegraph': {'ats': 'greenhouse', 'token': 'sourcegraph'},
    'Val Town': {'ats': 'ashby', 'token': 'valtown'},
    'WandB': {'ats': 'ashby', 'token': 'wandb'},
    'Warp': {'ats': 'ashby', 'token': 'warp'},
    'Block / Square': {'ats': 'smartrecruiters', 'token': 'Block'},
    'Celonis': {'ats': 'smartrecruiters', 'token': 'Celonis'},
    'Modern Treasury': {'ats': 'greenhouse', 'token': 'moderntreasury'},
    'N26': {'ats': 'personio', 'token': 'n26'},
    'Palantir': {'ats': 'lever', 'token': 'palantir'},
    'Shopify': {'ats': 'lever', 'token': 'shopify'},
    'Trade Republic': {'ats': 'personio', 'token': 'traderepublic'},
    'Twilio': {'ats': 'lever', 'token': 'twilio'},
    'Typeform': {'ats': 'workable', 'token': 'typeform'},
    'Ubisoft': {'ats': 'smartrecruiters', 'token': 'Ubisoft'},

    # --- Frontier AI & LLM Startups ---
    'Sierra': {'ats': 'ashby', 'token': 'sierra'},
    'Poolside': {'ats': 'greenhouse', 'token': 'poolside'},
    'Physical Intelligence': {'ats': 'ashby', 'token': 'pi'},
    'Midjourney': {'ats': 'ashby', 'token': 'midjourney'},
    'Luma AI': {'ats': 'ashby', 'token': 'lumaai'},
    'Pika': {'ats': 'ashby', 'token': 'pika'},
    'World Labs': {'ats': 'ashby', 'token': 'worldlabs'},
    'Scribe AI': {'ats': 'ashby', 'token': 'scribe'},
    'Jasper AI': {'ats': 'ashby', 'token': 'jasper'},
    'Copy.ai': {'ats': 'lever', 'token': 'copyai'},
    'Contextual AI': {'ats': 'ashby', 'token': 'contextual'},
    'Granola': {'ats': 'ashby', 'token': 'granola'},

    # --- Developer Experience & Infrastructure ---
    'Neon Database': {'ats': 'greenhouse', 'token': 'neon'},
    'Turso': {'ats': 'ashby', 'token': 'turso'},
    'Upstash': {'ats': 'ashby', 'token': 'upstash'},
    'Inngest': {'ats': 'ashby', 'token': 'inngest'},
    'Trigger.dev': {'ats': 'ashby', 'token': 'trigger'},
    'Fly.io': {'ats': 'greenhouse', 'token': 'flyio'},
    'Koyeb': {'ats': 'workable', 'token': 'koyeb'},
    'PostHog': {'ats': 'ashby', 'token': 'posthog'},
    'Mixpanel': {'ats': 'greenhouse', 'token': 'mixpanel'},
    'Amplitude': {'ats': 'greenhouse', 'token': 'amplitude'},
    'Segment': {'ats': 'greenhouse', 'token': 'segment'},

    # --- Mobile & Flutter Ecosystem & Mobile Platforms ---
    'RevenueCat': {'ats': 'ashby', 'token': 'revenuecat'},
    'Superwall': {'ats': 'ashby', 'token': 'superwall'},
    'Appwrite': {'ats': 'ashby', 'token': 'appwrite'},
    'OneSignal': {'ats': 'greenhouse', 'token': 'onesignal'},
    'Expo': {'ats': 'ashby', 'token': 'expo'},
    'Ionic': {'ats': 'greenhouse', 'token': 'ionic'},
    'Snapchat': {'ats': 'greenhouse', 'token': 'snapchat'},
    'Discord': {'ats': 'greenhouse', 'token': 'discord'},
    'Twitch': {'ats': 'greenhouse', 'token': 'twitch'},
    'Roku': {'ats': 'greenhouse', 'token': 'roku'},
    'Sonos': {'ats': 'greenhouse', 'token': 'sonos'},
    'Strava': {'ats': 'greenhouse', 'token': 'strava'},
    'AllTrails': {'ats': 'ashby', 'token': 'alltrails'},
    'Calm': {'ats': 'greenhouse', 'token': 'calm'},
    'Oura': {'ats': 'greenhouse', 'token': 'oura'},
    'Whoop': {'ats': 'greenhouse', 'token': 'whoop'},
    'Flo Health': {'ats': 'workable', 'token': 'flo'},
    'ClassDojo': {'ats': 'greenhouse', 'token': 'classdojo'},
    'Quizlet': {'ats': 'greenhouse', 'token': 'quizlet'},
    'Photomath': {'ats': 'workable', 'token': 'photomath'},
    'Tinder': {'ats': 'greenhouse', 'token': 'tinder'},
    'Hinge': {'ats': 'greenhouse', 'token': 'hinge'},
    'Life360': {'ats': 'greenhouse', 'token': 'life360'},
    'Deliveroo': {'ats': 'greenhouse', 'token': 'deliveroo'},
    'Grab': {'ats': 'greenhouse', 'token': 'grab'},
    'Gojek': {'ats': 'greenhouse', 'token': 'gojek'},
    'AppLovin': {'ats': 'greenhouse', 'token': 'applovin'},
    'IronSource': {'ats': 'greenhouse', 'token': 'ironsource'},
    'Unity': {'ats': 'greenhouse', 'token': 'unity'},
    'Epic Games': {'ats': 'greenhouse', 'token': 'epicgames'},
    'Roblox': {'ats': 'ashby', 'token': 'roblox'},
    'Supercell': {'ats': 'greenhouse', 'token': 'supercell'},
    'Riot Games': {'ats': 'greenhouse', 'token': 'riotgames'},
    'Niantic': {'ats': 'greenhouse', 'token': 'niantic'},
    'Branch Metrics': {'ats': 'greenhouse', 'token': 'branch'},
    'AppsFlyer': {'ats': 'greenhouse', 'token': 'appsflyer'},
    'Adjust': {'ats': 'personio', 'token': 'adjust'},
    'Singular': {'ats': 'greenhouse', 'token': 'singular'},
    'Adapty': {'ats': 'ashby', 'token': 'adapty'},
    'Qonversion': {'ats': 'ashby', 'token': 'qonversion'},
    'Emerge Tools': {'ats': 'ashby', 'token': 'emergetools'},
    'Embrace (Mobile)': {'ats': 'ashby', 'token': 'embrace'},
    'Instabug': {'ats': 'greenhouse', 'token': 'instabug'},
    'Bitrise': {'ats': 'greenhouse', 'token': 'bitrise'},
    'Codemagic': {'ats': 'workable', 'token': 'codemagic'},
    'Purchasely': {'ats': 'ashby', 'token': 'purchasely'},
    'Apphud': {'ats': 'ashby', 'token': 'apphud'},
    'TelemetryDeck': {'ats': 'ashby', 'token': 'telemetrydeck'},
    'LottieFiles': {'ats': 'ashby', 'token': 'lottiefiles'},
    'Mapbox': {'ats': 'greenhouse', 'token': 'mapbox'},
    'Radar': {'ats': 'ashby', 'token': 'radar'},
    'HyperTrack': {'ats': 'greenhouse', 'token': 'hypertrack'},
    'Bugsnag': {'ats': 'greenhouse', 'token': 'bugsnag'},
    'LogRocket': {'ats': 'greenhouse', 'token': 'logrocket'},
    'BrowserStack': {'ats': 'greenhouse', 'token': 'browserstack'},
    'Sauce Labs': {'ats': 'greenhouse', 'token': 'saucelabs'},
    'Stream (GetStream)': {'ats': 'ashby', 'token': 'stream'},
    'Sendbird': {'ats': 'greenhouse', 'token': 'sendbird'},
    '100ms': {'ats': 'ashby', 'token': '100ms'},
    'Daily.co': {'ats': 'ashby', 'token': 'daily'},
    'CometChat': {'ats': 'ashby', 'token': 'cometchat'},
    'PubNub': {'ats': 'greenhouse', 'token': 'pubnub'},
    'Ably': {'ats': 'greenhouse', 'token': 'ably'},

    # --- Mobile Mobility, Rideshare & Micro-mobility ---
    'Lime': {'ats': 'greenhouse', 'token': 'lime'},
    'Bird': {'ats': 'greenhouse', 'token': 'bird'},
    'Tier Mobility': {'ats': 'personio', 'token': 'tier'},
    'Voi': {'ats': 'teamtailor', 'token': 'voi'},
    'Via': {'ats': 'greenhouse', 'token': 'via'},
    'Cabify': {'ats': 'lever', 'token': 'cabify'},
    'BlaBlaCar': {'ats': 'greenhouse', 'token': 'blablacar'},
    'Dott': {'ats': 'greenhouse', 'token': 'dott'},
    'Forest (Micro-mobility)': {'ats': 'ashby', 'token': 'forest'},

    # --- Mobile Media, Creator & Consumer Apps ---
    'SoundCloud': {'ats': 'greenhouse', 'token': 'soundcloud'},
    'Deezer': {'ats': 'greenhouse', 'token': 'deezer'},
    'Patreon': {'ats': 'greenhouse', 'token': 'patreon'},
    'Substack': {'ats': 'ashby', 'token': 'substack'},
    'Medium': {'ats': 'lever', 'token': 'medium'},
    'VSCO': {'ats': 'greenhouse', 'token': 'vsco'},
    'Picsart': {'ats': 'greenhouse', 'token': 'picsart'},
    'Photoroom': {'ats': 'ashby', 'token': 'photoroom'},
    'Superhuman': {'ats': 'ashby', 'token': 'superhuman'},
    'Locket Widget': {'ats': 'ashby', 'token': 'locket'},
    'BeReal': {'ats': 'greenhouse', 'token': 'bereal'},
    'Lightricks': {'ats': 'greenhouse', 'token': 'lightricks'},
    'Sketch': {'ats': 'personio', 'token': 'sketch'},

    # --- Mobile Dating, Social & Messaging Apps ---
    'Grindr': {'ats': 'greenhouse', 'token': 'grindr'},
    'Feeld': {'ats': 'ashby', 'token': 'feeld'},
    'Raya': {'ats': 'ashby', 'token': 'raya'},
    'Thursday': {'ats': 'ashby', 'token': 'thursday'},
    'Pure': {'ats': 'ashby', 'token': 'pure'},
    'Yubo': {'ats': 'greenhouse', 'token': 'yubo'},
    'Partiful': {'ats': 'ashby', 'token': 'partiful'},
    'Signal': {'ats': 'greenhouse', 'token': 'signal'},

    # --- Mobile Health, Fitness & Connected Hardware ---
    'Noom': {'ats': 'greenhouse', 'token': 'noom'},
    'MyFitnessPal': {'ats': 'greenhouse', 'token': 'myfitnesspal'},
    'Sweatcoin': {'ats': 'lever', 'token': 'sweatcoin'},
    'Peloton': {'ats': 'greenhouse', 'token': 'peloton'},
    'Freeletics': {'ats': 'personio', 'token': 'freeletics'},
    'Clue': {'ats': 'personio', 'token': 'clue'},
    'Tonal': {'ats': 'greenhouse', 'token': 'tonal'},
    'Eight Sleep': {'ats': 'ashby', 'token': 'eightsleep'},
    'Ultrahuman': {'ats': 'ashby', 'token': 'ultrahuman'},
    'Levels': {'ats': 'ashby', 'token': 'levels'},
    'Komoot': {'ats': 'personio', 'token': 'komoot'},
    'Zwift': {'ats': 'greenhouse', 'token': 'zwift'},
    'Withings': {'ats': 'greenhouse', 'token': 'withings'},
    'Wyze': {'ats': 'greenhouse', 'token': 'wyze'},
    'Ecobee': {'ats': 'greenhouse', 'token': 'ecobee'},

    # --- Mobile Neobanks, Wallet & Fintech Apps ---
    'Starling Bank': {'ats': 'greenhouse', 'token': 'starlingbank'},
    'Bunq': {'ats': 'recruitee', 'token': 'bunq'},
    'Chipper Cash': {'ats': 'ashby', 'token': 'chippercash'},
    'Wave Money': {'ats': 'ashby', 'token': 'wave'},
    'Phantom Wallet': {'ats': 'ashby', 'token': 'phantom'},
    'Rainbow Wallet': {'ats': 'ashby', 'token': 'rainbow'},
    'Trust Wallet': {'ats': 'greenhouse', 'token': 'trustwallet'},
    'Coinbase': {'ats': 'greenhouse', 'token': 'coinbase'},
    'Nubank': {'ats': 'greenhouse', 'token': 'nubank'},
    'Current': {'ats': 'greenhouse', 'token': 'current'},
    'Dave': {'ats': 'greenhouse', 'token': 'dave'},
    'Cleo': {'ats': 'ashby', 'token': 'cleo'},
    'Remitly': {'ats': 'greenhouse', 'token': 'remitly'},
    'Flutterwave': {'ats': 'greenhouse', 'token': 'flutterwave'},
    'Paystack': {'ats': 'greenhouse', 'token': 'paystack'},
    'Kuda Bank': {'ats': 'workable', 'token': 'kuda'},
    'Public.com': {'ats': 'ashby', 'token': 'public'},
    'TradingView': {'ats': 'greenhouse', 'token': 'tradingview'},
    'eToro': {'ats': 'greenhouse', 'token': 'etoro'},
    'Binance': {'ats': 'lever', 'token': 'binance'},
    'Bitpanda': {'ats': 'personio', 'token': 'bitpanda'},
    'MoonPay': {'ats': 'ashby', 'token': 'moonpay'},
    'Argent': {'ats': 'ashby', 'token': 'argent'},
    'Zerion': {'ats': 'ashby', 'token': 'zerion'},
    'Family Wallet': {'ats': 'ashby', 'token': 'family'},

    # --- Mobile EdTech, Books & Media Apps ---
    'Babbel': {'ats': 'personio', 'token': 'babbel'},
    'Kahoot!': {'ats': 'greenhouse', 'token': 'kahoot'},
    'Brainly': {'ats': 'greenhouse', 'token': 'brainly'},
    'Brilliant.org': {'ats': 'ashby', 'token': 'brilliant'},
    'Blinkist': {'ats': 'personio', 'token': 'blinkist'},
    'Headway': {'ats': 'ashby', 'token': 'headway'},
    'Wattpad': {'ats': 'greenhouse', 'token': 'wattpad'},
    'Webtoon': {'ats': 'greenhouse', 'token': 'webtoon'},
    'Tidal': {'ats': 'greenhouse', 'token': 'tidal'},
    'Audiomack': {'ats': 'greenhouse', 'token': 'audiomack'},
    'Splice': {'ats': 'greenhouse', 'token': 'splice'},
    'Yousician': {'ats': 'personio', 'token': 'yousician'},

    # --- Mobile Delivery, Quick Commerce & Local Services ---
    'Glovo': {'ats': 'greenhouse', 'token': 'glovo'},
    'Rappi': {'ats': 'greenhouse', 'token': 'rappi'},
    'iFood': {'ats': 'greenhouse', 'token': 'ifood'},
    'Getir': {'ats': 'greenhouse', 'token': 'getir'},
    'Gopuff': {'ats': 'greenhouse', 'token': 'gopuff'},
    'Zepto': {'ats': 'ashby', 'token': 'zepto'},
    'Blinkit': {'ats': 'greenhouse', 'token': 'blinkit'},
    'Swiggy': {'ats': 'greenhouse', 'token': 'swiggy'},
    'Zomato': {'ats': 'greenhouse', 'token': 'zomato'},
    'Careem': {'ats': 'greenhouse', 'token': 'careem'},
    'InDrive': {'ats': 'greenhouse', 'token': 'indrive'},

    # --- Mobile E-Commerce & Marketplace Apps ---
    'Mercado Libre': {'ats': 'greenhouse', 'token': 'mercadolibre'},
    'Coupang': {'ats': 'greenhouse', 'token': 'coupang'},
    'Mercari': {'ats': 'greenhouse', 'token': 'mercari'},
    'Poshmark': {'ats': 'greenhouse', 'token': 'poshmark'},
    'Depop': {'ats': 'greenhouse', 'token': 'depop'},
    'StockX': {'ats': 'greenhouse', 'token': 'stockx'},
    'GOAT': {'ats': 'greenhouse', 'token': 'goat'},
    'Vinted': {'ats': 'greenhouse', 'token': 'vinted'},
    'Etsy': {'ats': 'greenhouse', 'token': 'etsy'},

    # --- Mobile Travel, Booking & Local Apps ---
    'GetYourGuide': {'ats': 'greenhouse', 'token': 'getyourguide'},
    'Klook': {'ats': 'greenhouse', 'token': 'klook'},
    'Headout': {'ats': 'greenhouse', 'token': 'headout'},
    'Omio': {'ats': 'personio', 'token': 'omio'},
    'Trainline': {'ats': 'greenhouse', 'token': 'trainline'},
    'FlixBus': {'ats': 'personio', 'token': 'flix'},
    'Zillow': {'ats': 'greenhouse', 'token': 'zillow'},
    'Redfin': {'ats': 'greenhouse', 'token': 'redfin'},
    'Rover': {'ats': 'greenhouse', 'token': 'rover'},
    'Care.com': {'ats': 'greenhouse', 'token': 'care'},
    'TaskRabbit': {'ats': 'greenhouse', 'token': 'taskrabbit'},
    'Thumbtack': {'ats': 'greenhouse', 'token': 'thumbtack'},

    # --- Global Unicorns & European Tech Giants ---
    'Revolut': {'ats': 'lever', 'token': 'revolut'},
    'Klarna': {'ats': 'personio', 'token': 'klarna'},
    'Wise': {'ats': 'smartrecruiters', 'token': 'Wise'},
    'Delivery Hero': {'ats': 'smartrecruiters', 'token': 'DeliveryHero'},
    'Just Eat Takeaway': {'ats': 'smartrecruiters', 'token': 'JustEatTakeaway'},
    'Wolt': {'ats': 'greenhouse', 'token': 'wolt'},
    'Personio (Company)': {'ats': 'personio', 'token': 'personio'},
    'Contentful': {'ats': 'greenhouse', 'token': 'contentful'},
    'Strapi': {'ats': 'greenhouse', 'token': 'strapi'},

    # --- Cybersecurity & Web3 ---
    'SentinelOne': {'ats': 'greenhouse', 'token': 'sentinelone'},
    'Chainlink': {'ats': 'greenhouse', 'token': 'chainlink'},
    'Consensys': {'ats': 'greenhouse', 'token': 'consensys'},
    'Uniswap': {'ats': 'ashby', 'token': 'uniswap'},
    'OpenSea': {'ats': 'ashby', 'token': 'opensea'},
    'Solana Labs': {'ats': 'ashby', 'token': 'solana'},
    'Circle (Crypto)': {'ats': 'greenhouse', 'token': 'circle'},
    'Fireblocks': {'ats': 'greenhouse', 'token': 'fireblocks'},

    # --- Regional Tech Aggregators ---
    'BuiltIn': {'ats': 'builtin', 'token': '*'},
    'The Hub (Nordics)': {'ats': 'thehub', 'token': '*'},
    'Wanted (APAC)': {'ats': 'wanted', 'token': '*'},
    'Get on Board (LATAM)': {'ats': 'getonbrd', 'token': '*'},
    'Programathor': {'ats': 'programathor', 'token': '*'},
    'Jobs.cz': {'ats': 'jobs_cz', 'token': '*'},
    'Jobs.ch': {'ats': 'jobsch', 'token': '*'},
    'Manfred (ES)': {'ats': 'manfred', 'token': '*'},

    # --- AI Coding, Vector & Data Platforms ---
    'Braintrust': {'ats': 'ashby', 'token': 'braintrust'},
    'Unstructured': {'ats': 'ashby', 'token': 'unstructured'},
    'Chroma': {'ats': 'ashby', 'token': 'chroma'},
    'Qdrant': {'ats': 'ashby', 'token': 'qdrant'},
    'LanceDB': {'ats': 'ashby', 'token': 'lancedb'},
    'Zilliz / Milvus': {'ats': 'greenhouse', 'token': 'zilliz'},
    'Cleanlab': {'ats': 'ashby', 'token': 'cleanlab'},
    'Codeium / Windsurf': {'ats': 'ashby', 'token': 'codeium'},
    'CodiumAI': {'ats': 'ashby', 'token': 'codium'},
    'Augment Code': {'ats': 'ashby', 'token': 'augment'},
    'Tabnine': {'ats': 'greenhouse', 'token': 'tabnine'},
    'BentoML': {'ats': 'ashby', 'token': 'bentoml'},

    # --- Data Engineering, Analytics & Orchestration ---
    'ClickHouse': {'ats': 'greenhouse', 'token': 'clickhouse'},
    'Timescale': {'ats': 'greenhouse', 'token': 'timescale'},
    'SingleStore': {'ats': 'greenhouse', 'token': 'singlestore'},
    'Confluent': {'ats': 'greenhouse', 'token': 'confluent'},
    'Astronomer': {'ats': 'greenhouse', 'token': 'astronomer'},
    'Dagster': {'ats': 'ashby', 'token': 'dagster'},
    'Prefect': {'ats': 'ashby', 'token': 'prefect'},
    'Airbyte': {'ats': 'ashby', 'token': 'airbyte'},
    'Hightouch': {'ats': 'ashby', 'token': 'hightouch'},
    'Census': {'ats': 'ashby', 'token': 'census'},
    'RudderStack': {'ats': 'ashby', 'token': 'rudderstack'},

    # --- Developer Auth, Identity & Security ---
    'Okta': {'ats': 'greenhouse', 'token': 'okta'},
    'Clerk': {'ats': 'ashby', 'token': 'clerk'},
    'Stytch': {'ats': 'ashby', 'token': 'stytch'},
    'WorkOS': {'ats': 'ashby', 'token': 'workos'},
    'Descope': {'ats': 'ashby', 'token': 'descope'},
    'Teleport': {'ats': 'greenhouse', 'token': 'gravitational'},
    'Chainguard': {'ats': 'greenhouse', 'token': 'chainguard'},
    'Semgrep': {'ats': 'greenhouse', 'token': 'semgrep'},
    'Twingate': {'ats': 'ashby', 'token': 'twingate'},

    # --- SaaS, Collaboration & Customer Ops ---
    'Pitch': {'ats': 'personio', 'token': 'pitch'},
    'Rive': {'ats': 'ashby', 'token': 'rive'},
    'Spline': {'ats': 'ashby', 'token': 'spline'},
    'Intercom': {'ats': 'greenhouse', 'token': 'intercom'},
    'Zendesk': {'ats': 'greenhouse', 'token': 'zendesk'},
    'Freshworks': {'ats': 'greenhouse', 'token': 'freshworks'},
    'Drift': {'ats': 'greenhouse', 'token': 'drift'},
    'Gong': {'ats': 'greenhouse', 'token': 'gong'},
    'Customer.io': {'ats': 'greenhouse', 'token': 'customerio'},
    'Postscript': {'ats': 'ashby', 'token': 'postscript'},
    'Yotpo': {'ats': 'greenhouse', 'token': 'yotpo'},

    # --- Fintech Infrastructure & Banking APIs ---
    'Navan': {'ats': 'greenhouse', 'token': 'navan'},
    'Flexport': {'ats': 'greenhouse', 'token': 'flexport'},
    'Toast': {'ats': 'greenhouse', 'token': 'toast'},
    'SoFi': {'ats': 'greenhouse', 'token': 'sofi'},
    'Marqeta': {'ats': 'greenhouse', 'token': 'marqeta'},
    'Lithic': {'ats': 'ashby', 'token': 'lithic'},
    'Unit': {'ats': 'ashby', 'token': 'unit'},
    'Column Bank': {'ats': 'ashby', 'token': 'column'},

    # --- National Public-Sector Aggregators ---
    'Arbetsförmedlingen (SE)': {'ats': 'arbetsformedlingen', 'token': 'arbetsformedlingen'},
    'Bundesagentur (DE)': {'ats': 'bundesagentur', 'token': 'bundesagentur'},
    'Eures (EU)': {'ats': 'eures', 'token': 'eures'},
    'USAJobs (US)': {'ats': 'usajobs', 'token': 'usajobs'},

    # --- UAE & Middle East Tech Scaleups ---
    'Careem (UAE)': {'ats': 'greenhouse', 'token': 'careem'},
    'Tabby (UAE/GCC BNPL)': {'ats': 'ashby', 'token': 'tabby'},
    'Tamara (UAE/KSA Fintech)': {'ats': 'ashby', 'token': 'tamara'},
    'Kitopi (UAE Kitchen Unicorn)': {'ats': 'greenhouse', 'token': 'kitopi'},
    'Noon (UAE E-Commerce)': {'ats': 'workable', 'token': 'noon'},
    'Property Finder (UAE PropTech)': {'ats': 'greenhouse', 'token': 'propertyfinder'},
    'Bayut & Dubizzle (UAE Tech)': {'ats': 'greenhouse', 'token': 'bayut'},
    'Ziina (UAE P2P Payments)': {'ats': 'ashby', 'token': 'ziina'},
    'Sarwa (UAE Investing)': {'ats': 'greenhouse', 'token': 'sarwa'},
    'Baraka (UAE Wealthtech)': {'ats': 'ashby', 'token': 'baraka'},
    'Lean Technologies (UAE Open Banking)': {'ats': 'ashby', 'token': 'lean'},
    'Rain (UAE/GCC Crypto)': {'ats': 'greenhouse', 'token': 'rain'},
    'CoinMENA (UAE Crypto)': {'ats': 'greenhouse', 'token': 'coinmena'},
    'Yalla Group (UAE Social/Gaming)': {'ats': 'greenhouse', 'token': 'yalla'},
    'Sirdab (GCC Mobile)': {'ats': 'workable', 'token': 'sirdab'},

    # --- AI Agents, Audio & LLM Scaleups ---
    'Groq': {'ats': 'ashby', 'token': 'groq'},
    'Mercor': {'ats': 'mercor', 'token': '*'},
    'Cerebras': {'ats': 'greenhouse', 'token': 'cerebras'},
    'SambaNova': {'ats': 'greenhouse', 'token': 'sambanova'},
    'Cartesia': {'ats': 'ashby', 'token': 'cartesia'},
    'LiveKit': {'ats': 'ashby', 'token': 'livekit'},
    'Deepgram': {'ats': 'ashby', 'token': 'deepgram'},
    'AssemblyAI': {'ats': 'ashby', 'token': 'assemblyai'},
    'Glif': {'ats': 'ashby', 'token': 'glif'},
    'Hyperwrite': {'ats': 'ashby', 'token': 'othersideai'},
    'Tome': {'ats': 'ashby', 'token': 'tome'},
    'Heptabase': {'ats': 'ashby', 'token': 'heptabase'},

    # --- Mobile Gaming & Interactive Studios ---
    'Pocket Gems': {'ats': 'greenhouse', 'token': 'pocketgems'},
    'Jam City': {'ats': 'greenhouse', 'token': 'jamcity'},
    'Peak Games': {'ats': 'greenhouse', 'token': 'peak'},
    'Dream Games': {'ats': 'personio', 'token': 'dreamgames'},
    'Nordeus': {'ats': 'greenhouse', 'token': 'nordeus'},
    'Wildlife Studios': {'ats': 'greenhouse', 'token': 'wildlife'},
    'Metacore': {'ats': 'teamtailor', 'token': 'metacore'},

    # --- Developer Infra, Backend & Observability ---
    'Better Stack': {'ats': 'ashby', 'token': 'betterstack'},
    'Axiom': {'ats': 'ashby', 'token': 'axiom'},
    'Highlight.io': {'ats': 'ashby', 'token': 'highlight'},
    'Knock': {'ats': 'ashby', 'token': 'knock'},
    'Svix': {'ats': 'ashby', 'token': 'svix'},
    'Hookdeck': {'ats': 'ashby', 'token': 'hookdeck'},
    'Deno': {'ats': 'ashby', 'token': 'deno'},
    'Bun': {'ats': 'ashby', 'token': 'bun'},
    'Nhost': {'ats': 'ashby', 'token': 'nhost'},
    'Convex': {'ats': 'ashby', 'token': 'convex'},
    'InstantDB': {'ats': 'ashby', 'token': 'instantdb'},

    # --- Mobile Security, Privacy & VPN Apps ---
    'Bitwarden': {'ats': 'greenhouse', 'token': 'bitwarden'},
    'Dashlane': {'ats': 'greenhouse', 'token': 'dashlane'},
    'Proton': {'ats': 'lever', 'token': 'proton'},
    'Mullvad VPN': {'ats': 'personio', 'token': 'mullvad'},
    'Nord Security': {'ats': 'personio', 'token': 'nordsecurity'},
    'ExpressVPN': {'ats': 'greenhouse', 'token': 'expressvpn'},

    # --- Mobile Audio, Podcasts & News Apps ---
    'Audible': {'ats': 'greenhouse', 'token': 'audible'},
    'Pocket Casts': {'ats': 'greenhouse', 'token': 'pocketcasts'},
    'TuneIn': {'ats': 'greenhouse', 'token': 'tunein'},
    'SmartNews': {'ats': 'greenhouse', 'token': 'smartnews'},
    'Flipboard': {'ats': 'greenhouse', 'token': 'flipboard'},
    'NewsBreak': {'ats': 'greenhouse', 'token': 'newsbreak'},
    'Inshorts': {'ats': 'greenhouse', 'token': 'inshorts'},
    'PocketFM': {'ats': 'ashby', 'token': 'pocketfm'},
    'Kuku FM': {'ats': 'ashby', 'token': 'kukufm'},


    # --- Additional High-Growth Tech Companies & Scaleups ---
    'Speakeasy API SDKs': {'ats': 'ashby', 'token': 'speakeasy'},
    'Val Town Serverless JS': {'ats': 'ashby', 'token': 'valtown'},
    'Modal Cloud Compute Labs': {'ats': 'ashby', 'token': 'modal'},
    'Pinecone Vector Platform': {'ats': 'ashby', 'token': 'pinecone'},
    'Chroma AI Database': {'ats': 'ashby', 'token': 'chroma'},
    'Qdrant Vector Engine': {'ats': 'ashby', 'token': 'qdrant'},
    'LanceDB Embeddings': {'ats': 'ashby', 'token': 'lancedb'},
    'LangChain LLM Frameworks': {'ats': 'ashby', 'token': 'langchain'},
    'LlamaIndex RAG Tools': {'ats': 'ashby', 'token': 'llamaindex'},
    'Braintrust AI Infrastructure': {'ats': 'ashby', 'token': 'braintrust'},
    'Cleanlab Data Quality AI': {'ats': 'ashby', 'token': 'cleanlab'},
    'BentoML Model Serving': {'ats': 'ashby', 'token': 'bentoml'},
    'Inngest Event Architecture': {'ats': 'ashby', 'token': 'inngest'},
    'Trigger.dev Background Tasks': {'ats': 'ashby', 'token': 'trigger'},
    'Svix Webhook Delivery': {'ats': 'ashby', 'token': 'svix'},
    'Hookdeck Webhook Infra': {'ats': 'ashby', 'token': 'hookdeck'},
    'Knock Notification System': {'ats': 'ashby', 'token': 'knock'},
    'Clerk Auth & User Mgmt': {'ats': 'ashby', 'token': 'clerk'},
    'Stytch Authentication': {'ats': 'ashby', 'token': 'stytch'},
    'WorkOS Enterprise Auth': {'ats': 'ashby', 'token': 'workos'},
    'Descope Identity Platform': {'ats': 'ashby', 'token': 'descope'},
    'Twingate Zero Trust Network': {'ats': 'ashby', 'token': 'twingate'},
    'PostHog Product Suite': {'ats': 'ashby', 'token': 'posthog'},
    'Dagster Pipeline Orchestrator': {'ats': 'ashby', 'token': 'dagster'},
    'Prefect Workflow Engine': {'ats': 'ashby', 'token': 'prefect'},
    'Airbyte Open Data Integration': {'ats': 'ashby', 'token': 'airbyte'},
    'Hightouch Reverse ETL': {'ats': 'ashby', 'token': 'hightouch'},
    'Census Operational Data': {'ats': 'ashby', 'token': 'census'},
    'RudderStack Customer Data': {'ats': 'ashby', 'token': 'rudderstack'},
    'Lithic Card Issuing API': {'ats': 'ashby', 'token': 'lithic'},
    'Unit Banking as a Service': {'ats': 'ashby', 'token': 'unit'},
    'Column Federal Banking API': {'ats': 'ashby', 'token': 'column'},
    'Ramp Financial Suite': {'ats': 'ashby', 'token': 'ramp'},
    'Deel Global Employment Platform': {'ats': 'ashby', 'token': 'deel'},
    'Linear Issue Tracker App': {'ats': 'ashby', 'token': 'linear'},
    'Notion All-in-One Workspace': {'ats': 'ashby', 'token': 'notion'},
    'Miro Collaborative Canvas': {'ats': 'ashby', 'token': 'miro'},
    'ClickUp Productivity Platform': {'ats': 'ashby', 'token': 'clickup'},
    'Loom Video Messaging App': {'ats': 'ashby', 'token': 'loom'},
    'Zapier Workflow Automation': {'ats': 'ashby', 'token': 'zapier'},
    'Sentry Application Performance': {'ats': 'ashby', 'token': 'sentry'},
    'Snowflake Cloud Data Warehouse': {'ats': 'ashby', 'token': 'snowflake'},
    'Snyk Developer Security Platform': {'ats': 'ashby', 'token': 'snyk'},
    'Supabase Firebase Alternative': {'ats': 'ashby', 'token': 'supabase'},
    'Temporal State Management': {'ats': 'ashby', 'token': 'temporal'},
    'Wiz Cloud Security Platform': {'ats': 'ashby', 'token': 'wiz'},
    'Redis In-Memory Database': {'ats': 'ashby', 'token': 'redis'},
    'Railway Deployment Platform': {'ats': 'ashby', 'token': 'railway'},
    'Whimsical Visual Workspace': {'ats': 'ashby', 'token': 'whimsical'},
    'Replit Cloud IDE Platform': {'ats': 'ashby', 'token': 'replit'},
    'ActiveCampaign Marketing': {'ats': 'greenhouse', 'token': 'activecampaign'},
    'Acquia Drupal Cloud': {'ats': 'greenhouse', 'token': 'acquia'},
    'Adobe Enterprise': {'ats': 'workday', 'token': 'adobe'},
    'Appian Low Code': {'ats': 'greenhouse', 'token': 'appian'},
    'AppDynamics APM': {'ats': 'greenhouse', 'token': 'appdynamics'},
    'Atlan Data Governance': {'ats': 'ashby', 'token': 'atlan'},
    'Autodesk CAD Software': {'ats': 'workday', 'token': 'autodesk'},
    'Automattic WordPress': {'ats': 'greenhouse', 'token': 'automattic'},
    'Avalara Tax Compliance': {'ats': 'greenhouse', 'token': 'avalara'},
    'BambooHR Software': {'ats': 'bamboohr', 'token': 'bamboohr'},
    'Basecamp 37signals': {'ats': 'workable', 'token': '37signals'},
    'BigCommerce Platform': {'ats': 'greenhouse', 'token': 'bigcommerce'},
    'Box Cloud Storage': {'ats': 'greenhouse', 'token': 'box'},
    'Braze Customer Engagement': {'ats': 'greenhouse', 'token': 'braze'},
    'Clari Revenue Platform': {'ats': 'greenhouse', 'token': 'clari'},
    'Cloudinary Media API': {'ats': 'greenhouse', 'token': 'cloudinary'},
    'Commure Healthcare Platform': {'ats': 'greenhouse', 'token': 'commure'},
    'CrowdStrike Security': {'ats': 'workday', 'token': 'crowdstrike'},
    'DataRobot Enterprise AI': {'ats': 'greenhouse', 'token': 'datarobot'},
    'DataStax Cassandra Cloud': {'ats': 'greenhouse', 'token': 'datastax'},
    'DigitalOcean Cloud Compute': {'ats': 'greenhouse', 'token': 'digitalocean'},
    'Dynatrace Observability Platform': {'ats': 'smartrecruiters', 'token': 'Dynatrace'},
    'Evernote Notes App': {'ats': 'greenhouse', 'token': 'evernote'},
    'Gatsby Web Platform': {'ats': 'greenhouse', 'token': 'gatsby'},
    'InVision Prototyping': {'ats': 'greenhouse', 'token': 'invision'},
    'KashFlow Accounting': {'ats': 'workable', 'token': 'kashflow'},
    'Klaviyo Email Automation': {'ats': 'greenhouse', 'token': 'klaviyo'},
    'LaunchDarkly Feature Platform': {'ats': 'greenhouse', 'token': 'launchdarkly'},
    'LogicMonitor Observability': {'ats': 'greenhouse', 'token': 'logicmonitor'},
    'LogMeIn GoTo Meetings': {'ats': 'greenhouse', 'token': 'goto'},
    'Lucid Visual Collaboration': {'ats': 'greenhouse', 'token': 'lucid'},
    'Modern Health Care': {'ats': 'ashby', 'token': 'modernhealth'},
    'Motive Fleet Safety': {'ats': 'greenhouse', 'token': 'motive'},
    'New Relic Performance': {'ats': 'greenhouse', 'token': 'newrelic'},
    'Outreach Revenue Sales': {'ats': 'greenhouse', 'token': 'outreach'},
    'PagerDuty Incident Response': {'ats': 'greenhouse', 'token': 'pagerduty'},
    'Pendo Product Analytics': {'ats': 'greenhouse', 'token': 'pendo'},
    'Ping Identity SSO': {'ats': 'greenhouse', 'token': 'pingidentity'},
    'Pluralsight Tech Learning': {'ats': 'greenhouse', 'token': 'pluralsight'},
    'Qualtrics Experience Mgmt': {'ats': 'greenhouse', 'token': 'qualtrics'},
    'Salesloft Engagement': {'ats': 'greenhouse', 'token': 'salesloft'},
    'Samsara IoT Operations': {'ats': 'greenhouse', 'token': 'samsara'},
    'ServiceTitan Trades Software': {'ats': 'greenhouse', 'token': 'servicetitan'},
    'Sitecore CMS Platform': {'ats': 'greenhouse', 'token': 'sitecore'},
    'Smartsheet Collaborative Work': {'ats': 'greenhouse', 'token': 'smartsheet'},
    'Splunk Log Analytics': {'ats': 'workday', 'token': 'splunk'},
    'Sprinklr Social Suite': {'ats': 'greenhouse', 'token': 'sprinklr'},
    'Squarespace Site Builder': {'ats': 'greenhouse', 'token': 'squarespace'},
    'Sumo Logic Analytics': {'ats': 'greenhouse', 'token': 'sumologic'},
    'SurveyMonkey Momentive': {'ats': 'greenhouse', 'token': 'momentive'},
    'ThoughtSpot Search BI': {'ats': 'greenhouse', 'token': 'thoughtspot'},
    'UserTesting Research Platform': {'ats': 'greenhouse', 'token': 'usertesting'},
    'Veeva Life Sciences': {'ats': 'greenhouse', 'token': 'veeva'},
    'Workiva Reporting': {'ats': 'greenhouse', 'token': 'workiva'},
    'Workato Enterprise Automation': {'ats': 'greenhouse', 'token': 'workato'},
    'Better Home Loans': {'ats': 'greenhouse', 'token': 'better'},
    'Bill Payables Platform': {'ats': 'greenhouse', 'token': 'bill'},
    'Capchase Non-Dilutive Capital': {'ats': 'ashby', 'token': 'capchase'},
    'Clearco Ecommerce Funding': {'ats': 'greenhouse', 'token': 'clearco'},
    'Clover Point of Sale': {'ats': 'greenhouse', 'token': 'clover'},
    'DuckDuckGo Privacy Search': {'ats': 'greenhouse', 'token': 'duckduckgo'},
    'Ethos Life Insurance': {'ats': 'greenhouse', 'token': 'ethos'},
    'Flywire Cross-Border Payments': {'ats': 'greenhouse', 'token': 'flywire'},
    'Fundbox Business Capital': {'ats': 'greenhouse', 'token': 'fundbox'},
    'GoCardless Direct Debit': {'ats': 'greenhouse', 'token': 'gocardless'},
    'Guideline 401k Retirement': {'ats': 'greenhouse', 'token': 'guideline'},
    'Hippo Digital Insurance': {'ats': 'greenhouse', 'token': 'hippo'},
    'Human Interest 401k': {'ats': 'greenhouse', 'token': 'humaninterest'},
    'Karat Creator Banking': {'ats': 'ashby', 'token': 'karat'},
    'Lemonade Insurtech': {'ats': 'greenhouse', 'token': 'lemonade'},
    'LendingClub Marketplace': {'ats': 'greenhouse', 'token': 'lendingclub'},
    'Melio B2B Payments': {'ats': 'greenhouse', 'token': 'melio'},
    'Method Financial Debt API': {'ats': 'ashby', 'token': 'method'},
    'Modern Treasury Money Movement': {'ats': 'greenhouse', 'token': 'moderntreasury'},
    'Next Insurance Commercial': {'ats': 'greenhouse', 'token': 'nextinsurance'},
    'Nova Credit Passport': {'ats': 'greenhouse', 'token': 'novacredit'},
    'Payoneer Global Payments': {'ats': 'greenhouse', 'token': 'payoneer'},
    'Petal Financial Credit': {'ats': 'greenhouse', 'token': 'petal'},
    'Pipe Recurring Revenue': {'ats': 'ashby', 'token': 'pipe'},
    'Qonto Business Banking': {'ats': 'greenhouse', 'token': 'qonto'},
    'Root Auto Insurance': {'ats': 'greenhouse', 'token': 'root'},
    'Sardine Fraud Prevention': {'ats': 'ashby', 'token': 'sardine'},
    'Sezzle Installment Payments': {'ats': 'greenhouse', 'token': 'sezzle'},
    'Shift4 Payment Processing': {'ats': 'greenhouse', 'token': 'shift4'},
    'Stash Wealth Investing': {'ats': 'greenhouse', 'token': 'stash'},
    'Tomo Credit Building': {'ats': 'ashby', 'token': 'tomo'},
    'Upstart AI Lending': {'ats': 'greenhouse', 'token': 'upstart'},
    'Vouch Startup Insurance': {'ats': 'greenhouse', 'token': 'vouch'},
    'Wealthfront Digital Wealth': {'ats': 'greenhouse', 'token': 'wealthfront'},
    'Zip Co BNPL Payments': {'ats': 'greenhouse', 'token': 'zipco'},
    'Benchling R&D Cloud': {'ats': 'greenhouse', 'token': 'benchling'},
    'Capsule Digital Pharmacy': {'ats': 'greenhouse', 'token': 'capsule'},
    'Carrot Fertility Benefits': {'ats': 'greenhouse', 'token': 'carrot'},
    'Cityblock Community Health': {'ats': 'greenhouse', 'token': 'cityblock'},
    'Clover Health Medicare': {'ats': 'greenhouse', 'token': 'cloverhealth'},
    'Devoted Health Senior Care': {'ats': 'greenhouse', 'token': 'devotedhealth'},
    'Doximity Physician Network': {'ats': 'greenhouse', 'token': 'doximity'},
    'Flatiron Health Oncology': {'ats': 'greenhouse', 'token': 'flatiron'},
    'Formlabs 3D Printing Tech': {'ats': 'greenhouse', 'token': 'formlabs'},
    'Hims & Hers Telehealth': {'ats': 'greenhouse', 'token': 'hims'},
    'Honor Senior Care Tech': {'ats': 'greenhouse', 'token': 'honor'},
    'Incredible Health Staffing': {'ats': 'greenhouse', 'token': 'incrediblehealth'},
    'Kyruus Patient Access': {'ats': 'greenhouse', 'token': 'kyruus'},
    'Lyra Health Mental Care': {'ats': 'greenhouse', 'token': 'lyrahealth'},
    'Maven Clinic Women Health': {'ats': 'greenhouse', 'token': 'mavenclinic'},
    'One Medical Primary Care': {'ats': 'greenhouse', 'token': 'onemedical'},
    'Oscar Health Insurance': {'ats': 'greenhouse', 'token': 'oscar'},
    'Outschool Live Classes': {'ats': 'greenhouse', 'token': 'outschool'},
    'Parsley Health Functional Care': {'ats': 'greenhouse', 'token': 'parsleyhealth'},
    'Ro Telehealth Platform': {'ats': 'greenhouse', 'token': 'ro'},
    'SonderMind Therapy Network': {'ats': 'greenhouse', 'token': 'sondermind'},
    'Strive Health Kidney Care': {'ats': 'greenhouse', 'token': 'strivehealth'},
    'Tempus AI Precision Medicine': {'ats': 'greenhouse', 'token': 'tempus'},
    'Tia Women Health Clinic': {'ats': 'greenhouse', 'token': 'tia'},
    'Zocdoc Appointment Booking': {'ats': 'greenhouse', 'token': 'zocdoc'},
    'Coursera Higher Education': {'ats': 'greenhouse', 'token': 'coursera'},
    'Datacamp Data Analytics': {'ats': 'greenhouse', 'token': 'datacamp'},
    'Guild Education Workforce': {'ats': 'greenhouse', 'token': 'guildeducation'},
    'Instructure Canvas LMS': {'ats': 'greenhouse', 'token': 'instructure'},
    'MasterClass Video Streaming': {'ats': 'greenhouse', 'token': 'masterclass'},
    'Newsela K-12 Content': {'ats': 'greenhouse', 'token': 'newsela'},
    'Skillshare Creative Classes': {'ats': 'greenhouse', 'token': 'skillshare'},
    'Udacity Tech Nanodegrees': {'ats': 'greenhouse', 'token': 'udacity'},
    'Udemy Global Courses': {'ats': 'greenhouse', 'token': 'udemy'},
    'Armis Device Security': {'ats': 'greenhouse', 'token': 'armis'},
    'Axonius Cyber Asset Mgmt': {'ats': 'greenhouse', 'token': 'axonius'},
    'Bitwarden Password Vault': {'ats': 'greenhouse', 'token': 'bitwarden'},
    'Cato Networks SASE': {'ats': 'greenhouse', 'token': 'catonetworks'},
    'Claroty Operational Tech': {'ats': 'greenhouse', 'token': 'claroty'},
    'Code42 Data Protection': {'ats': 'greenhouse', 'token': 'code42'},
    'Deep Instinct AI Security': {'ats': 'greenhouse', 'token': 'deepinstinct'},
    'Drata Automated Compliance': {'ats': 'ashby', 'token': 'drata'},
    'Illumio Microsegmentation': {'ats': 'greenhouse', 'token': 'illumio'},
    'Lacework Cloud Protection': {'ats': 'greenhouse', 'token': 'lacework'},
    'Netskope Cloud Security SASE': {'ats': 'greenhouse', 'token': 'netskope'},
    'Noname API Protection': {'ats': 'greenhouse', 'token': 'nonamesecurity'},
    'Orca Security Agentless': {'ats': 'greenhouse', 'token': 'orcasecurity'},
    'ReliaQuest Threat Detection': {'ats': 'greenhouse', 'token': 'reliaquest'},
    'Rubrik Data Security': {'ats': 'greenhouse', 'token': 'rubrik'},
    'SentinelOne Autonomous Security': {'ats': 'greenhouse', 'token': 'sentinelone'},
    'Socure Digital Identity': {'ats': 'greenhouse', 'token': 'socure'},
    'Tessian Email Protection': {'ats': 'greenhouse', 'token': 'tessian'},
    'Yubico Security Keys': {'ats': 'greenhouse', 'token': 'yubico'},
    'About You Online Fashion': {'ats': 'personio', 'token': 'aboutyou'},
    'Auto1 Car Platform': {'ats': 'personio', 'token': 'auto1'},
    'Celonis Enterprise Process': {'ats': 'smartrecruiters', 'token': 'Celonis'},
    'Chrono24 Watch Platform': {'ats': 'personio', 'token': 'chrono24'},
    'FlixBus Mobility Europe': {'ats': 'personio', 'token': 'flix'},
    'Flowkey Piano Learning': {'ats': 'personio', 'token': 'flowkey'},
    'Gett Mobility Europe': {'ats': 'greenhouse', 'token': 'gett'},
    'Klarna Banking Europe': {'ats': 'personio', 'token': 'klarna'},
    'Kuda Bank Mobile Africa': {'ats': 'workable', 'token': 'kuda'},
    'Metacore Games Finland': {'ats': 'teamtailor', 'token': 'metacore'},
    'N26 Neobank Europe': {'ats': 'personio', 'token': 'n26'},
    'Omio European Travel': {'ats': 'personio', 'token': 'omio'},
    'Personio HR Software': {'ats': 'personio', 'token': 'personio'},
    'Pitch Presentations Europe': {'ats': 'personio', 'token': 'pitch'},
    'Relive Video Journeys': {'ats': 'personio', 'token': 'relive'},
    'Resident Advisor Electronic': {'ats': 'personio', 'token': 'residentadvisor'},
    'Tier Mobility Europe': {'ats': 'personio', 'token': 'tier'},
    'Tiqets Culture Tickets': {'ats': 'personio', 'token': 'tiqets'},
    'Trade Republic Broker Europe': {'ats': 'personio', 'token': 'traderepublic'},
    'Trivago Hotel Search': {'ats': 'personio', 'token': 'trivago'},
    'Yousician Music Practice': {'ats': 'personio', 'token': 'yousician'},
    'Zalando Fashion Tech': {'ats': 'smartrecruiters', 'token': 'Zalando'},
    'Accura AI Tech': {'ats': 'ashby', 'token': 'accura'},
    'Acorns Micro Investing': {'ats': 'greenhouse', 'token': 'acorns'},
    'Ampere Cloud Chips': {'ats': 'greenhouse', 'token': 'amperecomputing'},
    'Apillon Web3 Dev': {'ats': 'ashby', 'token': 'apillon'},
    'Aptos Blockchain Labs': {'ats': 'greenhouse', 'token': 'aptoslabs'},
    'Arbitrum Offchain Labs': {'ats': 'greenhouse', 'token': 'offchainlabs'},
    'Axelar Interoperability': {'ats': 'ashby', 'token': 'axelar'},
    'Backblaze Storage Cloud': {'ats': 'greenhouse', 'token': 'backblaze'},
    'Betterment Digital Robo': {'ats': 'greenhouse', 'token': 'betterment'},

    # --- Global Tech Unicorns & Scaleups Batch 2 ---
    'Akamai Cloud': {'ats': 'greenhouse', 'token': 'akamai'},
    'Alation Data': {'ats': 'greenhouse', 'token': 'alation'},
    'AlertMedia Safety': {'ats': 'greenhouse', 'token': 'alertmedia'},
    'Alkymi Data': {'ats': 'ashby', 'token': 'alkymi'},
    'Alloy Identity': {'ats': 'greenhouse', 'token': 'alloy'},
    'Alteryx Analytics': {'ats': 'greenhouse', 'token': 'alteryx'},
    'Altana AI': {'ats': 'ashby', 'token': 'altana'},
    'Anaplan Planning': {'ats': 'greenhouse', 'token': 'anaplan'},
    'Anomalie AI': {'ats': 'greenhouse', 'token': 'anomalie'},
    'AnswerRocket BI': {'ats': 'greenhouse', 'token': 'answerrocket'},
    'Anterior AI': {'ats': 'ashby', 'token': 'anterior'},
    'Apna Job Network': {'ats': 'greenhouse', 'token': 'apna'},
    'Apollo.io Revenue': {'ats': 'greenhouse', 'token': 'apolloio'},
    'Appcues Onboarding': {'ats': 'greenhouse', 'token': 'appcues'},
    'AppOmni Security': {'ats': 'greenhouse', 'token': 'appomni'},
    'Apptronik Robotics': {'ats': 'ashby', 'token': 'apptronik'},
    'Aquabyte AI': {'ats': 'greenhouse', 'token': 'aquabyte'},
    'Ariga Ent': {'ats': 'ashby', 'token': 'ariga'},
    'Assembled Workforce': {'ats': 'ashby', 'token': 'assembled'},
    'Astria AI': {'ats': 'ashby', 'token': 'astria'},
    'Ather Energy': {'ats': 'greenhouse', 'token': 'atherenergy'},
    'Atlas Governance': {'ats': 'greenhouse', 'token': 'atlas'},
    'Aura Security': {'ats': 'greenhouse', 'token': 'aura'},
    'Avionos Tech': {'ats': 'greenhouse', 'token': 'avionos'},
    'Backstage Atlassian': {'ats': 'lever', 'token': 'atlassian'},
    'Balto AI': {'ats': 'greenhouse', 'token': 'balto'},
    'Basis AI': {'ats': 'ashby', 'token': 'basis'},
    'Beam Benefits': {'ats': 'greenhouse', 'token': 'beam'},
    'Beat Mobility': {'ats': 'greenhouse', 'token': 'beat'},
    'Behavioral Health Tech': {'ats': 'greenhouse', 'token': 'behavioralhealth'},
    'Beyond Identity': {'ats': 'greenhouse', 'token': 'beyondidentity'},
    'Bite Squad': {'ats': 'greenhouse', 'token': 'bitesquad'},
    'Bitso Exchange': {'ats': 'greenhouse', 'token': 'bitso'},
    'Bitwarden Vault': {'ats': 'greenhouse', 'token': 'bitwarden'},
    'BlackLocus Analytics': {'ats': 'greenhouse', 'token': 'blacklocus'},
    'Blameless SRE': {'ats': 'greenhouse', 'token': 'blameless'},
    'Bland AI': {'ats': 'ashby', 'token': 'bland'},
    'Blend Mortgage': {'ats': 'greenhouse', 'token': 'blend'},
    'Bluelight Security': {'ats': 'greenhouse', 'token': 'bluelight'},
    'Boku Payments': {'ats': 'greenhouse', 'token': 'boku'},
    'Bolt Financial': {'ats': 'ashby', 'token': 'bolt'},
    'BorderX Commerce': {'ats': 'greenhouse', 'token': 'borderx'},
    'Braze Engagement Tech': {'ats': 'greenhouse', 'token': 'braze'},
    'Breeze Airways': {'ats': 'greenhouse', 'token': 'breeze'},
    'Bridgetown AI': {'ats': 'ashby', 'token': 'bridgetown'},
    'Bridgeline Digital': {'ats': 'greenhouse', 'token': 'bridgeline'},
    'Bright Health': {'ats': 'greenhouse', 'token': 'brighthealth'},
    'Bringg Logistics': {'ats': 'greenhouse', 'token': 'bringg'},
    'Brsk Broadband': {'ats': 'greenhouse', 'token': 'brsk'},
    'Buddy Media': {'ats': 'greenhouse', 'token': 'buddymedia'},
    'Bugcrowd Security': {'ats': 'greenhouse', 'token': 'bugcrowd'},
    'Bumble Trading Platform': {'ats': 'ashby', 'token': 'bumble'},
    'BuzzFeed Media': {'ats': 'greenhouse', 'token': 'buzzfeed'},
    'Bytedance Global': {'ats': 'workable', 'token': 'bytedance'},
    'Cadence Design': {'ats': 'greenhouse', 'token': 'cadence'},
    'Calyx AI': {'ats': 'ashby', 'token': 'calyx'},
    'Canva Visual Design': {'ats': 'smartrecruiters', 'token': 'Canva'},
    'Capitalize Retirement': {'ats': 'greenhouse', 'token': 'capitalize'},
    'Careem Rides Asia': {'ats': 'greenhouse', 'token': 'careem'},
    'Carrum Health': {'ats': 'greenhouse', 'token': 'carrumhealth'},
    'Cast AI Cloud': {'ats': 'ashby', 'token': 'castai'},
    'Catalog Data': {'ats': 'greenhouse', 'token': 'catalog'},
    'Celestial AI': {'ats': 'greenhouse', 'token': 'celestialai'},
    'Celonis Process Mining': {'ats': 'smartrecruiters', 'token': 'Celonis'},
    'Chainalysis Web3 Security': {'ats': 'greenhouse', 'token': 'chainalysis'},
    'Checkr Background Verification': {'ats': 'greenhouse', 'token': 'checkr'},
    'Chime Bank US': {'ats': 'greenhouse', 'token': 'chime'},
    'Chroma Vector Search': {'ats': 'ashby', 'token': 'chroma'},
    'Chronosphere Observability': {'ats': 'greenhouse', 'token': 'chronosphere'},
    'CipherTrace Crypto': {'ats': 'greenhouse', 'token': 'ciphertrace'},
    'Citystorage Logistics': {'ats': 'greenhouse', 'token': 'citystorage'},
    'Clari Revenue Management': {'ats': 'greenhouse', 'token': 'clari'},
    'Cleanlab Data Quality': {'ats': 'ashby', 'token': 'cleanlab'},
    'Clever Education': {'ats': 'greenhouse', 'token': 'clever'},
    'ClickUp Workplace OS': {'ats': 'ashby', 'token': 'clickup'},
    'Clockwork Logistics': {'ats': 'greenhouse', 'token': 'clockwork'},
    'Cloudera Data Cloud': {'ats': 'greenhouse', 'token': 'cloudera'},
    'Coactive AI Visual': {'ats': 'ashby', 'token': 'coactive'},
    'Coda Collaborative Docs': {'ats': 'lever', 'token': 'Coda'},
    'Code42 CrashPlan': {'ats': 'greenhouse', 'token': 'code42'},
    'Codeium Developer AI': {'ats': 'ashby', 'token': 'codeium'},
    'CoinTracker Tax': {'ats': 'ashby', 'token': 'cointracker'},
    'Collective Freelance': {'ats': 'greenhouse', 'token': 'collective'},
    'Comma.ai Autonomous': {'ats': 'greenhouse', 'token': 'commaai'},
    'Commure Health Tech': {'ats': 'greenhouse', 'token': 'commure'},
    'Compass Real Estate': {'ats': 'greenhouse', 'token': 'compass'},
    'Compound Finance': {'ats': 'ashby', 'token': 'compound'},
    'Conducto DevOps': {'ats': 'greenhouse', 'token': 'conducto'},
    'Contextual AI Engine': {'ats': 'ashby', 'token': 'contextual'},
    'Cora AI': {'ats': 'ashby', 'token': 'cora'},
    'Cord In-App Chat': {'ats': 'ashby', 'token': 'cord'},
    'Cortex Developer Portal': {'ats': 'ashby', 'token': 'cortex'},
    'Couchbase Database': {'ats': 'greenhouse', 'token': 'couchbase'},
    'Coupang E-Commerce': {'ats': 'greenhouse', 'token': 'coupang'},
    'Cradle Biotech AI': {'ats': 'ashby', 'token': 'cradle'},
    'Credo AI Governance': {'ats': 'ashby', 'token': 'credoai'},
    'Cresta Sales AI': {'ats': 'greenhouse', 'token': 'cresta'},
    'Cribl Data Engine': {'ats': 'greenhouse', 'token': 'cribl'},
    'Crisp Analytics': {'ats': 'greenhouse', 'token': 'crisp'},
    'Cruise Autonomous': {'ats': 'greenhouse', 'token': 'getcruise'},
    'Cryptio Crypto Accounting': {'ats': 'ashby', 'token': 'cryptio'},
    'Crypto.com Exchange': {'ats': 'greenhouse', 'token': 'cryptocom'},
    'Culture Amp HR': {'ats': 'greenhouse', 'token': 'cultureamp'},
    'D-Wave Quantum': {'ats': 'greenhouse', 'token': 'dwave'},
    'Dagger CI/CD': {'ats': 'ashby', 'token': 'dagger'},
    'Dairy.com Logistics': {'ats': 'greenhouse', 'token': 'dairy'},
    'Dataiku Data Science': {'ats': 'greenhouse', 'token': 'dataiku'},
    'DataStax Cassandra': {'ats': 'greenhouse', 'token': 'datastax'},
    'Dave Banking Tech': {'ats': 'greenhouse', 'token': 'dave'},
    'DeepL Translation Engine': {'ats': 'ashby', 'token': 'deepl'},
    'DeepMind Intelligence': {'ats': 'google', 'token': '*'},
    'Deepnote Data Notebooks': {'ats': 'ashby', 'token': 'deepnote'},
    'Delphix Data Ops': {'ats': 'greenhouse', 'token': 'delphix'},
    'Denodo Data Virtualization': {'ats': 'greenhouse', 'token': 'denodo'},
    'Dialpad AI Communications': {'ats': 'greenhouse', 'token': 'dialpad'},
    'Domino Data Lab': {'ats': 'greenhouse', 'token': 'dominodatalab'},
    'DoorDash Delivery': {'ats': 'greenhouse', 'token': 'doordashusa'},
    'Doximity Medical Network': {'ats': 'greenhouse', 'token': 'doximity'},
    'Dremio Data Lakehouse': {'ats': 'greenhouse', 'token': 'dremio'},
    'Drift Conversational Marketing': {'ats': 'greenhouse', 'token': 'drift'},
    'Driver AI Docs': {'ats': 'ashby', 'token': 'driverai'},
    'Dtubes Video': {'ats': 'greenhouse', 'token': 'dtubes'},
    'Dune Analytics Web3': {'ats': 'ashby', 'token': 'dune'},
    'Duolingo Education': {'ats': 'breezy', 'token': 'duolingo'},
    'Dyte Video SDK': {'ats': 'ashby', 'token': 'dyte'},
    'Echo AI Platform': {'ats': 'ashby', 'token': 'echoai'},
    'Ecobee Smart Thermostats': {'ats': 'greenhouse', 'token': 'ecobee'},
    'Edge Impulse Embedded AI': {'ats': 'greenhouse', 'token': 'edgeimpulse'},
    'Eigen Layer Ethereum': {'ats': 'ashby', 'token': 'eigenlayer'},
    'Eight Sleep Smart Bed': {'ats': 'ashby', 'token': 'eightsleep'},
    'Elasticsearch Search': {'ats': 'greenhouse', 'token': 'elastic'},
    'ElevenLabs Voice AI': {'ats': 'ashby', 'token': 'elevenlabs'},
    'Ema Enterprise AI': {'ats': 'ashby', 'token': 'ema'},
    'Emerge Mobile Profiler': {'ats': 'ashby', 'token': 'emergetools'},
    'Envestnet Yodlee': {'ats': 'greenhouse', 'token': 'envestnet'},
    'Etsy Marketplace Platform': {'ats': 'greenhouse', 'token': 'etsy'},
    'Eventbrite Tickets': {'ats': 'greenhouse', 'token': 'eventbrite'},
    'Everlaw E-Discovery': {'ats': 'greenhouse', 'token': 'everlaw'},
    'Evidation Health': {'ats': 'greenhouse', 'token': 'evidation'},
    'Exact Sciences Bio': {'ats': 'greenhouse', 'token': 'exactsciences'},
    'Exodus Crypto Wallet': {'ats': 'greenhouse', 'token': 'exodus'},
    'ExpressVPN Privacy': {'ats': 'greenhouse', 'token': 'expressvpn'},
    'Faire Online Wholesale': {'ats': 'greenhouse', 'token': 'faire'},
    'FanDuel Gaming': {'ats': 'greenhouse', 'token': 'fanduel'},
    'Fastly Edge Compute': {'ats': 'greenhouse', 'token': 'fastly'},
    'Figma Design Systems': {'ats': 'greenhouse', 'token': 'figma'},
    'Fireblocks Crypto Infra': {'ats': 'greenhouse', 'token': 'fireblocks'},
    'Fivetran Pipeline Data': {'ats': 'greenhouse', 'token': 'fivetran'},
    'Flexport Freight Tech': {'ats': 'greenhouse', 'token': 'flexport'},
    'FlixBus Travel Europe': {'ats': 'personio', 'token': 'flix'},
    'Flo Health Femtech': {'ats': 'workable', 'token': 'flo'},
    'Fly.io Infrastructure': {'ats': 'greenhouse', 'token': 'flyio'},
    'Formlabs 3D Printers': {'ats': 'greenhouse', 'token': 'formlabs'},
    'Freshworks Customer Suite': {'ats': 'greenhouse', 'token': 'freshworks'},
    'Front Customer Operations': {'ats': 'greenhouse', 'token': 'front'},
    'Ginkgo Bioworks Synthetic': {'ats': 'greenhouse', 'token': 'ginkgobioworks'},
    'GitLab DevOps Engineering': {'ats': 'greenhouse', 'token': 'gitlab'},
    'Glean Enterprise Search': {'ats': 'ashby', 'token': 'glean'},
    'Glovo Delivery App': {'ats': 'greenhouse', 'token': 'glovo'},
    'Gong Revenue Intelligence': {'ats': 'greenhouse', 'token': 'gong'},
    'Grafana Observability Labs': {'ats': 'greenhouse', 'token': 'grafanalabs'},
    'Grindr Social Platform': {'ats': 'greenhouse', 'token': 'grindr'},
    'Groq Hardware AI': {'ats': 'ashby', 'token': 'groq'},
    'Gusto Payroll Platform': {'ats': 'greenhouse', 'token': 'gusto'},
    'Harness Software Delivery': {'ats': 'greenhouse', 'token': 'harness'},
    'Harvey Legal AI': {'ats': 'ashby', 'token': 'harvey'},
    'HashiCorp Cloud Tools': {'ats': 'greenhouse', 'token': 'hashicorp'},
    'Headspace Meditation App': {'ats': 'greenhouse', 'token': 'hs'},
    'Height Tasks': {'ats': 'ashby', 'token': 'height'},
    'Helicone AI Analytics': {'ats': 'ashby', 'token': 'helicone'},
    'Hinge Dating App': {'ats': 'greenhouse', 'token': 'hinge'},
    'Hopper Travel Booking': {'ats': 'bamboohr', 'token': 'hopper'},
    'HubSpot Marketing Suite': {'ats': 'greenhouse', 'token': 'hubspot'},
    'Hugging Face Machine Learning': {'ats': 'workable', 'token': 'huggingface'},
    'Hume Voice AI Labs': {'ats': 'ashby', 'token': 'hume'},
    'Hyperskill Tech Education': {'ats': 'ashby', 'token': 'hyperskill'},
    'Incredible Health Nursing': {'ats': 'greenhouse', 'token': 'incrediblehealth'},
    'Instacart Grocery Delivery': {'ats': 'greenhouse', 'token': 'instacart'},
    'Instabase Data AI': {'ats': 'greenhouse', 'token': 'instabase'},
    'Intercom Customer Platform': {'ats': 'greenhouse', 'token': 'intercom'},
    'Ironclad Contracting': {'ats': 'greenhouse', 'token': 'ironclad'},
    'Jasper Copywriting AI': {'ats': 'ashby', 'token': 'jasper'},
    'Joby Aviation Aerospace': {'ats': 'greenhouse', 'token': 'jobyaviation'},
    'Just Eat Takeaway Europe': {'ats': 'smartrecruiters', 'token': 'JustEatTakeaway'},
    'Klaviyo E-Commerce Marketing': {'ats': 'greenhouse', 'token': 'klaviyo'},
    'Kraken Crypto Platform': {'ats': 'lever', 'token': 'kraken'},
    'LangChain LLM Framework': {'ats': 'ashby', 'token': 'langchain'},
    'LaunchDarkly Feature Flags': {'ats': 'greenhouse', 'token': 'launchdarkly'},
    'LendingClub Digital Banking': {'ats': 'greenhouse', 'token': 'lendingclub'},
    'Linear Issue Management': {'ats': 'ashby', 'token': 'linear'},
    'LiveKit Realtime Voice API': {'ats': 'ashby', 'token': 'livekit'},
    'LogRocket Experience Analytics': {'ats': 'greenhouse', 'token': 'logrocket'},
    'Loom Video Recording': {'ats': 'ashby', 'token': 'loom'},
    'Luma AI 3D Capture': {'ats': 'ashby', 'token': 'lumaai'},
    'Lyft Transportation': {'ats': 'greenhouse', 'token': 'lyft'},
    'Mapbox Location SDKs': {'ats': 'greenhouse', 'token': 'mapbox'},
    'MasterClass Video Courses': {'ats': 'greenhouse', 'token': 'masterclass'},
    'Mercado Libre LatAm': {'ats': 'greenhouse', 'token': 'mercadolibre'},
    'Mercury Business Bank': {'ats': 'ashby', 'token': 'mercury'},
    'Miro Whiteboarding Software': {'ats': 'ashby', 'token': 'miro'},
    'Mistral AI Europe': {'ats': 'lever', 'token': 'mistral'},
    'Mixpanel Product Analytics': {'ats': 'greenhouse', 'token': 'mixpanel'},
    'Modal Serverless GPU': {'ats': 'ashby', 'token': 'modal'},
    'MongoDB NoSQL DB': {'ats': 'greenhouse', 'token': 'mongodb'},
    'Monzo Digital Banking': {'ats': 'greenhouse', 'token': 'monzo'},
    'N26 Neobank Tech': {'ats': 'personio', 'token': 'n26'},
    'Navan Travel Expense': {'ats': 'greenhouse', 'token': 'navan'},
    'Neon Postgres Database': {'ats': 'greenhouse', 'token': 'neon'},
    'Netlify Web Automation': {'ats': 'bamboohr', 'token': 'netlify'},
    'Netsanity Security': {'ats': 'greenhouse', 'token': 'netsanity'},
    'Netskope Cloud Security': {'ats': 'greenhouse', 'token': 'netskope'},
    'Notion Workspace Software': {'ats': 'ashby', 'token': 'notion'},
    'Nubank Latin America': {'ats': 'greenhouse', 'token': 'nubank'},
    'Okta Identity Management': {'ats': 'greenhouse', 'token': 'okta'},
    'OpenAI Artificial Intelligence': {'ats': 'ashby', 'token': 'openai'},
    'OpenSea NFT Marketplace': {'ats': 'ashby', 'token': 'opensea'},
    'Oscar Health Coverage': {'ats': 'greenhouse', 'token': 'oscar'},
    'Oura Smart Health Ring': {'ats': 'greenhouse', 'token': 'oura'},
    'Palantir Data Systems': {'ats': 'lever', 'token': 'palantir'},
    'Peloton Connected Fitness': {'ats': 'greenhouse', 'token': 'peloton'},
    'Perplexity AI Search': {'ats': 'ashby', 'token': 'perplexity'},
    'Pinecone Vector Index': {'ats': 'ashby', 'token': 'pinecone'},
    'Plaid Financial APIs': {'ats': 'greenhouse', 'token': 'plaid'},
    'PostHog Product Analytics': {'ats': 'ashby', 'token': 'posthog'},
    'Postman API Platform': {'ats': 'greenhouse', 'token': 'postman'},
    'Prefect Workflow Orchestration': {'ats': 'ashby', 'token': 'prefect'},
    'Qdrant Vector Database': {'ats': 'ashby', 'token': 'qdrant'},
    'Ramp Spend Management': {'ats': 'ashby', 'token': 'ramp'},
    'Redis Data Platform': {'ats': 'ashby', 'token': 'redis'},
    'Redfin Real Estate Tech': {'ats': 'greenhouse', 'token': 'redfin'},
    'Replit Online IDE': {'ats': 'ashby', 'token': 'replit'},
    'Resend Email API': {'ats': 'ashby', 'token': 'resend'},
    'Revolut Banking App': {'ats': 'lever', 'token': 'revolut'},
    'Rippling Workforce Platform': {'ats': 'rippling', 'token': 'rippling'},
    'Robinhood Investing App': {'ats': 'greenhouse', 'token': 'robinhood'},
    'Roblox Gaming Platform': {'ats': 'ashby', 'token': 'roblox'},
    'Rover Pet Services': {'ats': 'greenhouse', 'token': 'rover'},
    'Rubrik Cyber Resilience': {'ats': 'greenhouse', 'token': 'rubrik'},
    'Runway Generative AI': {'ats': 'ashby', 'token': 'runway-ml'},
    'Salesforce Cloud OS': {'ats': 'workday', 'token': 'salesforce.wd12.myworkdayjobs.com/wday/cxs/salesforce/External_Career_Site'},
    'Scale AI Data Platform': {'ats': 'greenhouse', 'token': 'scaleai'},
    'Shopify Ecommerce Engine': {'ats': 'lever', 'token': 'shopify'},
    'Sierra AI Customer Agents': {'ats': 'ashby', 'token': 'sierra'},
    'Signal Private Messaging': {'ats': 'greenhouse', 'token': 'signal'},
    'Slack Messaging App': {'ats': 'workday', 'token': 'salesforce.wd12.myworkdayjobs.com/wday/cxs/salesforce/slack'},
    'Snowflake Cloud Data': {'ats': 'ashby', 'token': 'snowflake'},
    'Snyk Developer Security': {'ats': 'ashby', 'token': 'snyk'},
    'SoFi Digital Finance': {'ats': 'greenhouse', 'token': 'sofi'},
    'Solana Foundation Labs': {'ats': 'ashby', 'token': 'solana'},
    'Sonos Smart Sound': {'ats': 'greenhouse', 'token': 'sonos'},
    'Sourcegraph Code Search': {'ats': 'greenhouse', 'token': 'sourcegraph'},
    'Spotify Audio Platform': {'ats': 'lever', 'token': 'spotify'},
    'Strava Athletic Tracking': {'ats': 'greenhouse', 'token': 'strava'},
    'Stripe Payment Gateway': {'ats': 'greenhouse', 'token': 'stripe'},
    'Substack Publication Platform': {'ats': 'ashby', 'token': 'substack'},
    'Supabase Database Platform': {'ats': 'ashby', 'token': 'supabase'},
    'Synthesia AI Video': {'ats': 'bamboohr', 'token': 'synthesia'},
    'Tailscale Mesh VPN': {'ats': 'greenhouse', 'token': 'tailscale'},
    'Temporal Orchestration Engine': {'ats': 'ashby', 'token': 'temporal'},
    'Toast Restaurant Software': {'ats': 'greenhouse', 'token': 'toast'},
    'Together AI Infrastructure': {'ats': 'greenhouse', 'token': 'togetherai'},
    'Tonal Smart Home Fitness': {'ats': 'greenhouse', 'token': 'tonal'},
    'Trade Republic Europe': {'ats': 'personio', 'token': 'traderepublic'},
    'TradingView Financial Charts': {'ats': 'greenhouse', 'token': 'tradingview'},
    'Twilio Communications API': {'ats': 'lever', 'token': 'twilio'},
    'Twitch Live Streaming': {'ats': 'greenhouse', 'token': 'twitch'},
    'Uber Global Mobility': {'ats': 'uber', 'token': '*'},
    'Udemy Education Platform': {'ats': 'greenhouse', 'token': 'udemy'},
    'Unity Technologies': {'ats': 'greenhouse', 'token': 'unity'},
    'Vanta Compliance Platform': {'ats': 'ashby', 'token': 'vanta'},
    'Vercel Frontend Platform': {'ats': 'greenhouse', 'token': 'vercel'},
    'Verkada Physical Security': {'ats': 'greenhouse', 'token': 'verkada'},
    'Vinted Fashion Marketplace': {'ats': 'greenhouse', 'token': 'vinted'},
    'Warp Intelligent Terminal': {'ats': 'ashby', 'token': 'warp'},
    'Wayfair Retail Platform': {'ats': 'smartrecruiters', 'token': 'Wayfair'},
    'Weaviate Vector DB': {'ats': 'greenhouse', 'token': 'weaviate'},
    'Webflow Web Engine': {'ats': 'greenhouse', 'token': 'webflow'},
    'Weights & Biases MLOps': {'ats': 'ashby', 'token': 'wandb'},
    'Wise Cross-Border Payments': {'ats': 'smartrecruiters', 'token': 'Wise'},
    'Wolt Delivery Services': {'ats': 'greenhouse', 'token': 'wolt'},
    'World Labs Spatial AI': {'ats': 'ashby', 'token': 'worldlabs'},
    'Writer AI Content': {'ats': 'ashby', 'token': 'writer'},
    'Zalando Ecommerce Giant': {'ats': 'smartrecruiters', 'token': 'Zalando'},
    'Zapier Integration Engine': {'ats': 'ashby', 'token': 'zapier'},
    'Zendesk Support Suite': {'ats': 'greenhouse', 'token': 'zendesk'},
    'Zillow Real Estate': {'ats': 'greenhouse', 'token': 'zillow'},
    'Zomato Food Tech': {'ats': 'greenhouse', 'token': 'zomato'},
    'Zoom Video Communications': {'ats': 'workday', 'token': 'zoom.wd5.myworkdayjobs.com/wday/cxs/zoom/zoom'},
    # --- Hybrid / General Job Boards ---
    'Welcome to the Jungle': {'ats': 'welcometothejungle', 'token': '*'},
    'We Work Remotely': {'ats': 'fallback', 'token': 'https://weworkremotely.com/remote-jobs.rss'},
    'RemoteOK': {'ats': 'remoteok', 'token': '*'},
    'Wellfound': {'ats': 'wellfound', 'token': '*'},
    'Y Combinator': {'ats': 'ycombinator', 'token': '*'},
    'Adzuna': {'ats': 'adzuna', 'token': '*'},
    'Jooble': {'ats': 'jooble', 'token': '*'},
    'Otta': {'ats': 'welcometothejungle', 'token': '*'},
    'FlexJobs': {'ats': 'flexjobs', 'token': '*'},
    'LinkedIn': {'ats': 'linkedin', 'token': '*'},
    'Indeed': {'ats': 'indeed', 'token': '*'},
}

# ==========================================
# 3. Notification Settings (Environment Vars)
# ==========================================
# Telegram configuration
TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
TELEGRAM_CHAT_ID = os.getenv("TELEGRAM_CHAT_ID")

# Google Sheets configuration
# Can be a path to a credentials JSON file or raw JSON content of the service account
GOOGLE_CREDENTIALS_JSON = os.getenv("GOOGLE_CREDENTIALS_JSON")
GOOGLE_SHEET_NAME = os.getenv("GOOGLE_SHEET_NAME", "Job Scraper Results")
GOOGLE_WORKSHEET_NAME = os.getenv("GOOGLE_WORKSHEET_NAME", "Jobs")

# Adzuna API configuration
ADZUNA_APP_ID = os.getenv("ADZUNA_APP_ID")
ADZUNA_APP_KEY = os.getenv("ADZUNA_APP_KEY")

# Jooble API configuration
JOOBLE_API_KEY = os.getenv("JOOBLE_API_KEY")

# Apify API configuration
APIFY_API_TOKEN = os.getenv("APIFY_API_TOKEN")
APIFY_LINKEDIN_ACTOR = os.getenv("APIFY_LINKEDIN_ACTOR", "curious_coder/linkedin-jobs-scraper")
APIFY_INDEED_ACTOR = os.getenv("APIFY_INDEED_ACTOR", "misceres/indeed-scraper")
APIFY_LINKEDIN_LOCATION = os.getenv("APIFY_LINKEDIN_LOCATION", "Remote")
APIFY_INDEED_LOCATION = os.getenv("APIFY_INDEED_LOCATION", "Remote")
APIFY_INDEED_COUNTRY = os.getenv("APIFY_INDEED_COUNTRY", "US")
